//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPClient.WCFServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceReference.ICurrentTimeContract")]
    public interface ICurrentTimeContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentTimeContract/GetData", ReplyAction="http://tempuri.org/ICurrentTimeContract/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrentTimeContract/GetData", ReplyAction="http://tempuri.org/ICurrentTimeContract/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrentTimeContractChannel : ASPClient.WCFServiceReference.ICurrentTimeContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrentTimeContractClient : System.ServiceModel.ClientBase<ASPClient.WCFServiceReference.ICurrentTimeContract>, ASPClient.WCFServiceReference.ICurrentTimeContract {
        
        public CurrentTimeContractClient() {
        }
        
        public CurrentTimeContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrentTimeContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrentTimeContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrentTimeContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
